# Generated by Django 2.2.1 on 2019-05-14 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name_customer', models.CharField(max_length=100)),
                ('email_customer', models.EmailField(max_length=254)),
                ('attended', models.BooleanField()),
                ('outcome', models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost'), ('Reschedule', 'Reschedule'), ('Cancelled', 'Cancelled')], max_length=12)),
                ('cash_collected', models.PositiveIntegerField()),
                ('call_notes', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
