# Generated by Django 2.2.1 on 2019-06-05 18:01

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190515_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
