# Generated by Django 2.2.1 on 2019-06-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190605_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='ref_id',
            new_name='id',
        ),
    ]
