# Generated by Django 2.2.1 on 2019-06-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20190609_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='recording_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
