# Generated by Django 2.2.1 on 2019-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_recording_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='call_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cash_collected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
