# Generated by Django 2.2.1 on 2019-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20190610_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='attended',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='email_customer',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
